name: Ansible-lint

on:
  push:
    branches-ignore: main
  pull_request:
    branches-ignore: main

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Lint Ansible Playbooks
      uses: ansible-community/ansible-lint-action@main
      with:
        path: "./ansible/"
