name: Ansible-lint

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  ansible:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Copy ansible.cfg
      run: |
        cp ./ansible/ansible.cfg ./ansible.cfg
        cp ./ansible/vault.key.example ./vault.key

    - name: Lint Ansible Playbooks
      uses: osism/ansible-lint-action@main
      with:
        targets: |
          ./ansible
        args: "-c ./ansible/.config/ansible-lint.yml"
