name: Terraform-validate

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  terraform:
    strategy:
      matrix:
        env: ["prod", "stage"]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.1.7

    - name: Create variables
      run: cp ./terraform/${{ matrix.env }}/terraform.tfvars.example ./terraform/${{ matrix.env }}/terraform.tfvars

    - name: Create variables
      run: rm ./terraform/${{ matrix.env }}/backend.tf

    - name: Terraform Init
      id: init
      run: terraform init
      working-directory: ./terraform/${{ matrix.env }}

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      working-directory: ./terraform/${{ matrix.env }}

  tflint:
    strategy:
      matrix:
        env: ["prod", "stage"]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout this repo
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - uses: terraform-linters/setup-tflint@v1
      name: Setup TFLint
      with:
        tflint_version: latest

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact ./terraform/${{ matrix.env }}
